name: Deploy Project
on: [issues]
jobs:
  llsten:
    runs-on: ubuntu-latest
    steps:
      - name: Issue info
        run: |
          echo "Issue #${{ github.event.issue.number }}"
          echo "Title: ${{ github.event.issue.title }}"
          echo "Author: ${{ github.event.issue.user.login }}"
          echo '${{ toJson(github) }}'
